export const Colors = {
  primary: '#00450d',
  primaryContainer: '#1b5e20',
  primaryFixed: '#acf4a4',
  primaryFixedDim: '#91d78a',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#90d689',
  onPrimaryFixed: '#002203',

  secondary: '#8d4f00',
  secondaryContainer: '#ff9c33',
  secondaryFixed: '#ffdcc0',
  secondaryFixedDim: '#ffb877',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#693900',

  tertiary: '#7c0007',
  tertiaryContainer: '#a60b12',
  tertiaryFixed: '#ffdad6',
  tertiaryFixedDim: '#ffb4ab',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#ffb2a9',

  surface: '#faf9f5',
  surfaceBright: '#faf9f5',
  surfaceContainer: '#efeeea',
  surfaceContainerLow: '#f4f4f0',
  surfaceContainerHigh: '#e9e8e4',
  surfaceContainerHighest: '#e3e2df',
  surfaceContainerLowest: '#ffffff',
  surfaceDim: '#dbdad6',
  surfaceVariant: '#e3e2df',
  surfaceTint: '#2a6b2c',
  onSurface: '#1b1c1a',
  onSurfaceVariant: '#41493e',
  onBackground: '#1b1c1a',
  background: '#faf9f5',

  outline: '#717a6d',
  outlineVariant: '#c0c9bb',
  inverseSurface: '#2f312e',
  inverseOnSurface: '#f2f1ed',
  inversePrimary: '#91d78a',

  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  onErrorContainer: '#93000a',
};
